lint:
  extends:
    - recommended
  rules:
    boolean-parameter-prefixes: off
    no-invalid-media-type-examples:
      severity: warn
      disallowAdditionalProperties: false
    no-enum-type-mismatch: off
