openapi: 3.0.3

info:
  title: Lob API
  version: "2020-02-11"
  description: >
    The Lob API is organized around REST. Our API is designed to have predictable,
    resource-oriented URLs and uses HTTP response codes to indicate any API errors
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal

servers:
  - url: https://api.lob.com/v1
    description: production

tags:
  - name: Addresses
    description: A frictionless address book for use with the print and mail API.

  - name: Asset URLs
    x-traitTag: true
    description: >-
      All asset URLs returned by the Lob API (postcards, letters, thumbnails,
      etc) are signed links served over HTTPS. All links returned will expire in
      30 days to prevent mis-sharing. Each time a GET request is initiated, a
      new signed URL will be generated.

  - name: Bank Accounts
    description: Bank Accounts allow you to store your bank account securely in our system.

  - name: Certificates
    description: A certificate store to manage client identities. Create, retrieve, update, and delete PEM certificates.

  - name: Letters
    description: Easily print and mail letters. Create, retrieve, cancel, and list letters.

  - name: Postcards
    description: Easily print and mail postcards. Create, retrieve, cancel, and list postcards.

  - name: Template Versions
    description: Versioning for your reusable HTML print and mail templates.

  - name: Templates
    description: Versioned, reusable HTML Templates for use with the print and mail API.

  - name: Test and Live Environments
    x-traitTag: true
    description: >-
      To make the API as explorable as possible, accounts have test and live
      environment API keys. You're not charged any fees in the test environment,
      so we encourage you to use it to try out services, perform quality
      assurance, and run automated testing. Objects―addresses, letters, checks,
      etc―in one environment cannot be manipulated by objects in the other.
      In general, a payment method (either credit card or ACH account) must be
      added to your account to make live API requests. However, a payment method
      is not required for the first 300 live requests per month to the
      `/v1/us_verifications` endpoint. After the first 300 requests, you will
      begin receiving errors with status code `403`.
      Requests made in the test environment always validate request arguments,
      simulate live environment behavior, and enforce rate limits. _They never
      print, mail nor, for verification services, verify addresses._ The US &
      International verification services trigger behavior with specific
      argument values, and, if you plan on using those, we recommend reading US
      Verification Test Environment and Int'l Verification Test Environment.
      To switch between environments, use the appropriate key for that
      environment when performing a request. You can find each environment's API
      key in your dashboard under Settings; test API keys are always prefixed
      with `test_` and production API keys with `live_`.

  - name: US Verifications
    description: >
      Validate, automatically correct, and standardize the addresses in your
      address book based on USPS's [Coding Accuracy Support System (CASS)](https://postalpro.usps.com/certifications/cass).

  - name: Zip Lookups
    description: >
      Find a list of cities, states and associated information about a US ZIP code.

x-tagGroups:
  - name: Overview
    tags:
      - Test and Live Environments
      - Asset URLs
      - Certificates

  - name: Print and Mail API
    tags:
      - Postcards
      - Letters
      - Bank Accounts
      - Addresses
      - Templates
      - Template Versions

  - name: US Verification API
    tags:
      - US Verifications
      - Zip Lookups

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:
  /addresses/{adr_id}:
    $ref: resources/addresses/address.yml

  /addresses:
    $ref: resources/addresses/addresses.yml

  /bank_accounts/{bank_id}/verify:
    $ref: resources/bank_accounts/bank_account_verify.yml

  /bank_accounts/{bank_id}:
    $ref: resources/bank_accounts/bank_account.yml

  /bank_accounts:
    $ref: resources/bank_accounts/bank_accounts.yml

  /certificates/{id}:
    $ref: resources/certificates/certificate.yml

  /certificates:
    $ref: resources/certificates/certificates.yml

  /letters/{ltr_id}:
    $ref: resources/letters/letter.yml

  /letters:
    $ref: resources/letters/letters.yml

  /postcards/{psc_id}:
    $ref: resources/postcards/postcard.yml

  /postcards:
    $ref: resources/postcards/postcards.yml

  /templates/{tmpl_id}/versions/{vrsn_id}:
    $ref: resources/templates/template_versions/template_version.yml

  /templates/{tmpl_id}/versions:
    $ref: resources/templates/template_versions/template_versions.yml

  /templates/{tmpl_id}/compile:
    $ref: resources/templates/template_compile.yml

  /templates/{tmpl_id}:
    $ref: resources/templates/template.yml

  /templates:
    $ref: resources/templates/templates.yml

  /us_verifications:
    $ref: resources/us_verifications/us_verifications.yml

  /us_zip_lookups:
    $ref: resources/zip_lookups/zip_lookups.yml
