openapi: 3.0.3

info:
  title: Lob API
  version: "2020-02-11"
  description: >
    The Lob API is organized around REST. Our API is designed to have predictable,
    resource-oriented URLs and uses HTTP response codes to indicate any API errors
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal

servers:
  - url: https://api.lob.com/v1
    description: production

tags:
  - name: Addresses
    description: A frictionless address book for use with the print and mail API.

  - name: API Keys
    x-traitTag: true
    description: |
      Lob authenticates your API requests using your account's API keys. 
      If you do not include your key when making an API request, or use 
      one that is incorrect or outdated, Lob returns an error with a `401` 
      HTTP response code. You can find all API keys in your dashboard under Settings.

      There are two types of API keys: *secret* and *publishable*.

      - **Secret API keys** should be kept confidential and only stored on your own servers. 
      Your account's secret API key can perform any API request to Lob without restriction.

      - **Publishable API keys** are limited to US verifications, international verifications, 
      and US autocomplete requests. While we encourage you to use a secret key for maximum 
      security, you can publish these keys to JavaScript code or in an Android or iPhone app 
      without exposing print and mail services or your secret key. Publishable keys are always 
      prefixed with `[environment]_pub`.

      Every type comes with a pair of keys: one for the testing environment and one for the 
      live environment. We recommend reading Test and Live Environments for more information.

  - name: Asset URLs
    x-traitTag: true
    description: >-
      All asset URLs returned by the Lob API (postcards, letters, thumbnails,
      etc) are signed links served over HTTPS. All links returned will expire in
      30 days to prevent mis-sharing. Each time a GET request is initiated, a
      new signed URL will be generated.

  - name: Bank Accounts
    description: Bank Accounts allow you to store your bank account securely in our system.

  - name: Beta Program
    description: |
      Here at Lob, we pride ourselves on building high quality platform capabilities rapidly 
      and iteratively, so we can constantly be delivering additional value to our customers. 
      When evaluating a new product or feature from Lob, you may see that it has been released in Beta.

      Typically, something in Beta means that the feature is early in its lifecycle here at 
      Lob. While we fully stand behind the quality of everything we release in Beta, we do 
      anticipate receiving a higher level of customer feedback on Beta features, as well as a 
      faster pace of changes from our engineering team in response to that feedback.

      By participating in a Lob Beta program, you will have the opportunity to get early access 
      to a new product capability, as well as having a unique opportunity to influence the product's 
      direction with your feedback.

      You should also anticipate that features in Beta may have functional or design limitations, 
      and might change rapidly as we receive customer feedback and make improvements. In particular, 
      new APIs in Beta may also go through more frequent versioning and version deprecation cycles 
      than our more mature APIs.

      If you are participating in a Beta program and want to provide feedback, please feel free to 
      [contact us](https://lob.com/support#contact)!

  - name: Bulk Int'l Verifications
    description: Verify a list of non-US addresses.

  - name: Bulk US Verifications
    description: Verify a list of US addresses.

  - name: Cancellation Windows
    x-traitTag: true
    description: |
      By default, all new accounts have a 5 minute cancellation window for postcards, 
      self mailers, letters, and checks. Within that timeframe, you can cancel 
      mailings from production, free of charge. Once the window has passed for a 
      postcard, self mailer, letter, or check, the mailing is no longer cancelable. 
      In addition, certain customers can customize their cancellation windows by 
      product in their [Dashboard Settings](https://dashboard.lob.com/#). Upgrade to 
      the appropriate [Print & Mail Edition](https://dashboard.lob.com/#/settings/editions) 
      to automatically gain access to this ability. For more details on this feature, 
      check out our [Cancellation Guide](https://lob.com/guides#cancellation_windows).

      If you schedule a postcard, self mailer, letter, or check for up to 180 days 
      in the future by supplying the `send_date` parameter, that will override any 
      cancellation window you may have for that product.

  - name: Certificates
    description: A certificate store to manage client identities.

  - name: Checks
    description: Checks allow you to send payments via physical checks.

  - name: Int'l Verifications
    description: Address verification for non-US addresses

  - name: Letters
    description: Easily print and mail letters.

  - name: Libraries
    x-traitTag: true
    description: |
      Please visit our [Github](https://www.github.com/lob) for a list of our supported libraries.
      - [Ruby](https://github.com/lob/lob-ruby)
      - [PHP](https://github.com/lob/lob-php)
      - [Node.js](https://github.com/lob/lob-node)
      - [Python](https://github.com/lob/lob-python)
      - [Java](https://github.com/lob/lob-java)
      - [Elixir](https://github.com/lob/lob-elixir)

  - name: Postcards
    description: Easily print and mail postcards.

  - name: Self Mailers
    description: Easily print and mail self mailers.

  - name: Template Versions
    description: Versioning for your reusable HTML print and mail templates.

  - name: Templates
    description: Versioned, reusable HTML Templates for use with the print and mail API.

  - name: Test and Live Environments
    x-traitTag: true
    description: >-
      To make the API as explorable as possible, accounts have test and live
      environment API keys. You're not charged any fees in the test environment,
      so we encourage you to use it to try out services, perform quality
      assurance, and run automated testing. Objects―addresses, letters, checks,
      etc―in one environment cannot be manipulated by objects in the other.
      In general, a payment method (either credit card or ACH account) must be
      added to your account to make live API requests. However, a payment method
      is not required for the first 300 live requests per month to the
      `/v1/us_verifications` endpoint. After the first 300 requests, you will
      begin receiving errors with status code `403`.
      Requests made in the test environment always validate request arguments,
      simulate live environment behavior, and enforce rate limits. _They never
      print, mail nor, for verification services, verify addresses._ The US &
      International verification services trigger behavior with specific
      argument values, and, if you plan on using those, we recommend reading US
      Verification Test Environment and Int'l Verification Test Environment.
      To switch between environments, use the appropriate key for that
      environment when performing a request. You can find each environment's API
      key in your dashboard under Settings; test API keys are always prefixed
      with `test_` and production API keys with `live_`.

  - name: US Autocompletions
    description: >
      Given partial address information, this endpoint returns up to 10 address suggestions.

  - name: US Verifications
    description: >
      Validate, automatically correct, and standardize the addresses in your
      address book based on USPS's [Coding Accuracy Support System (CASS)](https://postalpro.usps.com/certifications/cass).

  - name: Webhooks
    x-traitTag: true
    description: |
      Webhooks are an easy way to get notifications on events happening asynchronously 
      within Lob's architecture. For example, when a postcard gets a "Processed For 
      Delivery" tracking event, an event object of type `postcard.processed_for_delivery` 
      will be created. If you are subscribed to that event type in that Environment 
      (Test vs. Live), Lob will send that event to any URLs you've specified via an 
      HTTP POST request. In Live mode, you can only have as many webhooks as allotted 
      in your current [Print & Mail Edition](https://dashboard.lob.com/#/settings/editions). 
      There is no limit in Test mode.

      You can view and create [webhooks](https://dashboard.lob.com/#/webhooks) on the 
      Lob Dashboard, as well as view your [events](https://dashboard.lob.com/#/events). 
      See our [Webhooks Integration Guide](https://lob.com/guides#webhooks_block) for more 
      details on how to integrate. Please see the full list of event types available for 
      subscription here.

  - name: Zip Lookups
    description: >
      Find a list of cities, states and associated information about a US ZIP code.

x-tagGroups:
  - name: Overview
    tags:
      - Test and Live Environments
      - Asset URLs
      - Certificates
      - API Keys
      - Webhooks
      - Cancellation Windows
      - Libraries
      - Beta Program

  - name: Print and Mail API
    tags:
      - Addresses
      - Postcards
      - Self Mailers
      - Letters
      - Checks
      - Bank Accounts
      - Templates
      - Template Versions

  - name: US Verification API
    tags:
      - Address Verification
      - Bulk US Verifications
      - US Autocompletions
      - Zip Lookups

  - name: Int'l Verification API
    tags:
      - Int'l Verifications
      - Bulk Int'l Verifications

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:
  /addresses/{adr_id}:
    $ref: resources/addresses/address.yml

  /addresses:
    $ref: resources/addresses/addresses.yml

  /bank_accounts/{bank_id}/verify:
    $ref: resources/bank_accounts/bank_account_verify.yml

  /bank_accounts/{bank_id}:
    $ref: resources/bank_accounts/bank_account.yml

  /bank_accounts:
    $ref: resources/bank_accounts/bank_accounts.yml

  /bulk/us_verifications:
    $ref: resources/bulk_us_verifications/bulk_us_verifications.yml

  /bulk/intl_verifications:
    $ref: resources/bulk_intl_verifications/bulk_intl_verifications.yml

  /certificates/{id}:
    $ref: resources/certificates/certificate.yml

  /certificates:
    $ref: resources/certificates/certificates.yml

  /checks/{chk_id}:
    $ref: resources/checks/check.yml

  /checks:
    $ref: resources/checks/checks.yml

  /intl_verifications:
    $ref: resources/intl_verifications/intl_verifications.yml

  /letters/{ltr_id}:
    $ref: resources/letters/letter.yml

  /letters:
    $ref: resources/letters/letters.yml

  /postcards/{psc_id}:
    $ref: resources/postcards/postcard.yml

  /postcards:
    $ref: resources/postcards/postcards.yml

  /self_mailers/{sfm_id}:
    $ref: resources/self_mailers/self_mailer.yml

  /self_mailers:
    $ref: resources/self_mailers/self_mailers.yml

  /templates/{tmpl_id}/versions/{vrsn_id}:
    $ref: resources/templates/template_versions/template_version.yml

  /templates/{tmpl_id}/versions:
    $ref: resources/templates/template_versions/template_versions.yml

  /templates/{tmpl_id}/compile:
    $ref: resources/templates/template_compile.yml

  /templates/{tmpl_id}:
    $ref: resources/templates/template.yml

  /templates:
    $ref: resources/templates/templates.yml

  /us_autocompletions:
    $ref: resources/us_autocompletions/us_autocompletions.yml

  /us_verifications:
    $ref: resources/us_verifications/us_verifications.yml

  /us_zip_lookups:
    $ref: resources/zip_lookups/zip_lookups.yml
