openapi: 3.0.3

info:
  title: Lob API
  version: "2020-02-11"
  description: >
    The Lob API is organized around REST. Our API is designed to have predictable,
    resource-oriented URLs and uses HTTP response codes to indicate any API errors
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal

servers:
  - url: https://api.lob.com/v1
    description: production

tags:
  - name: Addresses
    description: A frictionless address book for use with the print and mail API.

  - name: Certificates
    description: A certificate store to manage client identities. Create, retrieve, update, and delete PEM certificates.

  - name: Letters
    description: Easily print and mail letters. Create, retrieve, cancel, and list letters.

  - name: Template_Versions
    description: Versioning for your reusable HTML print and mail templates.

  - name: Templates
    description: Versioned, reusable HTML Templates for use with the print and mail API.

  - name: US Verifications
    description: >
      Validate, automatically correct, and standardize the addresses in your
      address book based on USPS's [Coding Accuracy Support System (CASS)](https://postalpro.usps.com/certifications/cass).

  - name: Zip Lookups
    description: >
      Find a list of cities, states and associated information about a US ZIP code.

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:
  /addresses/{adr_id}:
    $ref: resources/addresses/address.yml

  /addresses:
    $ref: resources/addresses/addresses.yml

  /certificates/{id}:
    $ref: resources/certificates/certificate.yml

  /certificates:
    $ref: resources/certificates/certificates.yml

  /letters/{ltr_id}:
    $ref: resources/letters/letter.yml

  /letters:
    $ref: resources/letters/letters.yml

  /templates/{tmpl_id}/versions/{vrsn_id}:
    $ref: resources/templates/template_versions/template_version.yml

  /templates/{tmpl_id}/versions:
    $ref: resources/templates/template_versions/template_versions.yml

  /templates/{tmpl_id}:
    $ref: resources/templates/template.yml

  /templates:
    $ref: resources/templates/templates.yml

  /us_verifications:
    $ref: resources/us_verifications/us_verifications.yml

  /us_zip_lookups:
    $ref: resources/zip_lookups/zip_lookups.yml
