openapi: 3.0.3

info:
  title: Lob API
  version: "2020-02-11"
  description: >
    The Lob API is organized around REST. Our API is designed to have predictable,
    resource-oriented URLs and uses HTTP response codes to indicate any API errors
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal

servers:
  - url: https://api.lob.com/v1
    description: production

tags:
  - name: Addresses
    description: Content relevant to addresses
  - name: US Verifications
    description: Content relevant to US verifications
  - name: Zip Lookups
    description: Content relevant to US ZIP lookups

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:
  /addresses/{id}:
    $ref: resources/addresses/address.yml

  /addresses:
    $ref: resources/addresses/addresses.yml

  /us_zip_lookups:
    $ref: resources/zip_lookups/zip_lookups.yml

  /us_verifications:
    $ref: resources/us_verifications/us_verifications.yml
