[[redirects]]
  from = "/node"
  to = "https://github.com/lob/lob-node"

[[redirects]]
  from = "/python"
  to = "https://github.com/lob/lob-python"

[[redirects]]
  from = "/ruby"
  to = "https://github.com/lob/lob-ruby"

[[redirects]]
  from = "/php"
  to = "https://github.com/lob/lob-php"

[[redirects]]
  from = "/java"
  to = "https://github.com/lob/lob-java"

[[redirects]]
  from = "/elixir"
  to = "https://github.com/lob/lob-elixir"
