name: CD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.LOBOT_TOKEN }}

      - name: Use .node-version Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: bundle
        shell: bash
        run: |
          set -x
          npm install
          npm run bundle

      - name: build zero-dependency docs
        shell: bash
        run: npm run redoc

      - name: build postman collection
        uses: ./actions/contract_tests
        with:
          testCommand: "npm run postman"
        env:
          LOB_API_TEST_TOKEN: ${{ secrets.LOB_API_TEST_TOKEN }}
          LOB_API_LIVE_TOKEN: ${{ secrets.LOB_API_LIVE_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
        id: extract_branch
