name: "Deploy to Netlify"

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Publish release to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.LOBOT_TOKEN }}
          ref: 'main'
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: create necessary files to push to deployment
        run: |
          npm install
          npm run bundle
          npm run postman
          npm run redoc
          npm run build
      - name: push to `deployment`
        run: |
          set -x
          git config --global user.name lobot
          git config --global user.email lobot@lob.com
          git update-index -q --refresh
          git add --force dist/lob-api-postman.json
          git add --force dist/lob-api-bundled.yml
          git add --force docs/index.html
          git commit -m "pushing builds" --no-verify
          git push --force origin main:deployment
      - name: Deploy production to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=docs --prod