name: CD_check

on: push

jobs:
  check:
    if: github.actor != 'lobot'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: am I pretty?
        uses: actionsx/prettier@v2
        with:
          args: --check

      - name: run spectral
        uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: "./Lob-API-public.yml"
          repo_token: ${{ github.token }}
          event_name: ${{ github.event_name }}

      - name: run contract tests
        uses: ./actions/contract_tests
        continue-on-error: true
        env:
          LOB_API_TEST_TOKEN: ${{ secrets.LOB_API_TEST_TOKEN }}

      - name: invoke build
        uses: benc-uk/workflow-dispatch@v1.1.0
        with:
          workflow: CD
          token: ${{ secrets.LOBOT_TOKEN }}
